---
- name: create includes folder
  file: path={{ monit_includes }} state=directory mode=0600

- name: create lib folder
  file: path="{{ monit_lib_folder }}" state=directory mode=0600
  
- name: config - Setup monitrc
  template:
    src: monitrc.j2
    dest: "{{monitrc_conf}}"
    owner: root
    group: root
    mode: 0700
  notify: restart monit