services:
  backend:
    build:
      context: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - backend
    