pipeline {
    agent {
        docker {
            image 'rikorose/gcc-cmake:8'
        }
    }
	parameters {
        booleanParam(name: 'BUILD_EXECUTABLE', defaultValue: false, description: '')
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mkdir -p build && cd build && cmake .. -DBUILD_EXECUTABLE=${params.BUILD_EXECUTABLE} && cmake --build . -j'
                archiveArtifacts artifacts: 'build/MyExecutable'
            }
        }
        stage('Test') {
            steps {
                sh 'cd build && ./MyExecutable'
            }
        }
    }
}
