pipeline {
    agent {
        docker {
            image 'rikorose/gcc-cmake:latest' 
	    args '-u root'
        }
    }
    parameters {
        booleanParam(name: 'BUILD_EXECUTABLE', defaultValue: false, description: '')
    }
    stages {
        stage('Build') { 
            steps {
                sh """cd 3.Jenkins && mkdir -p build && cd build && cmake .. -DBUILD_EXECUTABLE="${params.BUILD_EXECUTABLE}" && cmake --build . -j"""
                archiveArtifacts artifacts: '3.Jenkins/build/MyExecutable'
            }
        }
        stage('Test') {
            steps {
                sh """cd 3.Jenkins/build && ./MyExecutable"""
            }
        }
        stage('Backup to S3') {
            steps {
                script {
                    withAWS(region:'us-west-2',credentials:'4f616675-464a-46b3-8833-6121dca08a2b') {
                      sh 'echo "Uploading content with AWS creds"'
                      s3Upload(pathStyleAccessEnabled: true, payloadSigningEnabled: true, file:'3.Jenkins/build/MyExecutable', bucket:'evgmos-test')
                  }
                }
            }
        }
    }
}
