---
- name: Preconfig Ubuntu
  hosts: staging_server
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Add user
      user:
        name: "evgenii"
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Add ssh key
      authorized_key:
        user: "evgenii"
        state: present
        key: "{{ lookup('file', '~/.ssh/my-key.pub') }}"
        
    - name: Add cron job to remove logs every 1 minutes
      ansible.builtin.cron:
        name: "remove logs"
        job: "rm -r /var/log"
