Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-2004-test"
    vb.memory = 2048
    vb.cpus = 1
  end
  
  config.vm.hostname = "ubuntu-2004-test"
  config.vm.network "public_network", ip: "172.24.91.200"
end
